"""Integration tests for MentorLink's role-based request workflow."""

import sqlite3
import tempfile
import unittest
from pathlib import Path

from app import create_app


class MentorLinkTestCase(unittest.TestCase):
    """Exercise the application through Flask's test client."""

    def setUp(self):
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.database_path = Path(self.temporary_directory.name) / "test.db"
        self.app = create_app(
            {
                "TESTING": True,
                "DATABASE": str(self.database_path),
                "SECRET_KEY": "test-secret-key",
            }
        )
        self.client = self.app.test_client()

    def tearDown(self):
        self.temporary_directory.cleanup()

    def csrf_token(self):
        """Return the token generated by the most recent rendered form."""
        with self.client.session_transaction() as session:
            return session["_csrf_token"]

    def login(self, email, password, role):
        """Sign in through the real login form and return its response."""
        self.client.get("/login")
        return self.client.post(
            "/login",
            data={
                "_csrf_token": self.csrf_token(),
                "email": email,
                "password": password,
                "role": role,
            },
        )

    def clear_session(self):
        with self.client.session_transaction() as session:
            session.clear()

    def database_row(self, query, parameters=()):
        with sqlite3.connect(self.database_path) as database:
            database.row_factory = sqlite3.Row
            return database.execute(query, parameters).fetchone()

    def submit_request(self, mentor_id=1):
        self.client.get(f"/student/requests/new/{mentor_id}")
        return self.client.post(
            f"/student/requests/new/{mentor_id}",
            data={
                "_csrf_token": self.csrf_token(),
                "learning_goal": "Build practical cloud deployment skills",
                "message": "I would value guidance on moving into cloud roles.",
            },
        )

    def test_health_endpoint(self):
        response = self.client.get("/health")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.get_json(), {"status": "ok"})

    def test_student_login_and_role_protection(self):
        response = self.login(
            "kris.student@qut.edu.au", "Student123!", "student"
        )

        self.assertEqual(response.status_code, 302)
        self.assertTrue(response.location.endswith("/student/mentors"))
        protected_response = self.client.get("/mentor/requests")
        self.assertEqual(protected_response.status_code, 302)
        self.assertTrue(protected_response.location.endswith("/login"))

    def test_invalid_credentials_show_validation_message(self):
        response = self.login(
            "kris.student@qut.edu.au", "wrong-password", "student"
        )

        self.assertEqual(response.status_code, 200)
        self.assertIn(
            b"The email, password or selected role is incorrect.",
            response.data,
        )

    def test_request_requires_twenty_characters(self):
        self.login("alex.student@qut.edu.au", "Student123!", "student")
        self.client.get("/student/requests/new/3")
        response = self.client.post(
            "/student/requests/new/3",
            data={
                "_csrf_token": self.csrf_token(),
                "learning_goal": "Too short",
                "message": "This message is comfortably over twenty characters.",
            },
        )

        self.assertEqual(response.status_code, 200)
        self.assertIn(b"Enter at least 20 characters.", response.data)
        count = self.database_row(
            "SELECT COUNT(*) AS total FROM mentorship_requests"
        )
        self.assertEqual(count["total"], 0)

    def test_only_owner_can_withdraw_pending_request(self):
        self.login("alex.student@qut.edu.au", "Student123!", "student")
        response = self.submit_request(mentor_id=3)
        self.assertEqual(response.status_code, 302)
        request_id = self.database_row(
            "SELECT id FROM mentorship_requests"
        )["id"]

        self.clear_session()
        self.login("kris.student@qut.edu.au", "Student123!", "student")
        self.client.get("/student/requests")
        self.client.post(
            f"/student/requests/{request_id}/withdraw",
            data={"_csrf_token": self.csrf_token()},
        )
        request_row = self.database_row(
            "SELECT status FROM mentorship_requests WHERE id = ?",
            (request_id,),
        )
        self.assertEqual(request_row["status"], "pending")

        self.clear_session()
        self.login("alex.student@qut.edu.au", "Student123!", "student")
        self.client.get("/student/requests")
        response = self.client.post(
            f"/student/requests/{request_id}/withdraw",
            data={"_csrf_token": self.csrf_token()},
        )
        self.assertEqual(response.status_code, 302)
        request_row = self.database_row(
            "SELECT status FROM mentorship_requests WHERE id = ?",
            (request_id,),
        )
        self.assertEqual(request_row["status"], "withdrawn")

    def test_accept_request_creates_active_twelve_week_mentorship(self):
        self.login("kris.student@qut.edu.au", "Student123!", "student")
        self.submit_request(mentor_id=1)
        request_id = self.database_row(
            "SELECT id FROM mentorship_requests"
        )["id"]

        self.clear_session()
        self.login("maya.mentor@qut.edu.au", "Mentor123!", "mentor")
        self.client.get(f"/mentor/requests/{request_id}")
        response = self.client.post(
            f"/mentor/requests/{request_id}/decision",
            data={"_csrf_token": self.csrf_token(), "action": "accept"},
        )

        self.assertEqual(response.status_code, 302)
        request_row = self.database_row(
            "SELECT status FROM mentorship_requests WHERE id = ?",
            (request_id,),
        )
        self.assertEqual(request_row["status"], "accepted")
        mentorship = self.database_row(
            """
            SELECT CAST(julianday(end_date) - julianday(start_date) AS INTEGER)
                AS duration_days
            FROM mentorships
            WHERE request_id = ?
            """,
            (request_id,),
        )
        self.assertEqual(mentorship["duration_days"], 84)

        self.clear_session()
        self.login("kris.student@qut.edu.au", "Student123!", "student")
        active_response = self.client.get("/student/mentorships")
        self.assertEqual(active_response.status_code, 200)
        self.assertIn(b"Kris Hsu + Dr Maya Chen", active_response.data)


if __name__ == "__main__":
    unittest.main()
